### ISSUE TITLE
Search using queryVars always return empty array

### ISSUE THREAD

**Issue by more-ginger** [lewisdonovan/google-news-scraper#61] opened 2024-10-21 15:10 UTC
Encountered this issue while trying to scrape articles for a selection of languages starting from a specific topic. Basically, it doesn't matter what I search or if I use `baseUrl` or `searchTerm`, if I include `queryVars` to search for languages aside from English I always get an empty array.

To keep it simple for this issue, I tested the snippet of code in the documentation. The behaviour seems to be the same. As parameters for my query:

```
const searchQuery = {
    searchTerm: "Últimas noticias en Madrid",
    queryVars: {
        hl:"es-ES",
        gl:"ES",
        ceid:"ES:es"
    },
}
```

When I scrape the results:

```
const articles = await googleNewsScraper(searchQuery);
```

This returns an empty array `[]`. 

If I change the paramaters to:

``` 
const searchQuery = {
    searchTerm: "Últimas noticias en Madrid"
}
```

The scraper returns an array with articles in Spanish, example:

```
{
    title: '¡Mbappé podría anunciar su fichaje por el Madrid en días!',
    link: 'https://news.google.com/read/CBMilAFBVV95cUxNRkFyX1RLNEZ0YWJvRFhKcTE4bzhGcDJySVJ0RE5ORFhiVUVzTmE2R0ExM19sTkYwaU94cjVwamktYXB2QW90VndfenFjUlhnVG9zRGc0aGNHU0NaZGJ0VDROX2k1b3VtYWxsY1NVdHJmV2tDWVFOOWtOOTNuYWxsYTg0OWhJWXhsX0xUMXAtVWZVSGgw0gGUAUFVX3lxTE9ZUW1aRVJhcl9hOFByaDR4MmtQVnVYUjRWaDkyZ01xUF9uM0hqTDcza0k3YmhhVjdfOGtGbTczRmNNVTV5MXdZTzNHSVFlbWxndncxSUNNUW13LXkxejlndWNqSVJUb3F0VlJ4TDJGMlpLaW5mRkE1Nm0tOXJXY1psV3lNOWZMZHpEUTg3UmFKT2FYQmY?hl=en-US&gl=US&ceid=US%3Aen',
    image: 'https://news.google.com/api/attachments/CC8iL0NnNUdOR0ZwVFc5RVpscHBWbE5VVFJDb0FSaXNBaWdCTWdtUklaUUluYWswUlFN=-w400-h224-p-df-rw',
    source: 'Sport',
    datetime: 2024-04-16T07:00:00.000Z,
    time: 'Apr 16',
    articleType: 'regular'
  }
```
As you can see from the `link` property, it works only because `searchTerm` is a string in Spanish, the last part of the url still assumes I am searching in the English language `...hl=en-US&gl=US&ceid=US%3Aen`. Any idea on what is going on here and how it can be solved? The `queryVars` parameter would be incredibly useful, as it would allow to filter out results in English.

**Comment by Gabriel-cdn** [comment] 2024-10-22 18:15
@more-ginger I faced the same issue. I was able to make it works removing the queryVars parameters and changing the baseUrl from `https://news.google.com/search` to `https://news.google.com.br/search` (In my case: Brazil Portuguese). I did not go deep to  figure out whats the root cause yet

**Comment by lewisdonovan** [comment] 2024-10-25 21:13
@more-ginger Thanks for flagging, I'll look into why this isn't working as expected and ship a fix once I find it (or update here if for some reason it's not possible).

**Comment by lewisdonovan** [comment] 2024-10-27 20:26
This was actually a really weird bug, but the fix is super simple. Removing the `hl` property from the `queryVars` object actually makes this work as expected. 

I say it's a weird bug because if I include the `hl` param in the URL in a browser (or even puppeteer running locally), the page loads fine. But running it through the scraper, the `hl` param breaks it for some reason

For example:
```javascript
const articles = await googleNewsScraper({
  searchTerm: "Últimas noticias en Madrid",
  queryVars: {
    gl: "ES",
    ceid: "ES:es"
  },
  logLevel: 'debug',
});
```

Or for Brazilian Portuguese @Gabriel-cdn 
```javascript
const articles = await googleNewsScraper({
  searchTerm: "Últimas notícias do Rio",
  queryVars: {
    gl: "PT",
    ceid: "PT:br"
  },
  logLevel: 'debug',
});
```

The fix is available in the latest version, please update. Hope this helps. 
I'm closing this ticket, feel free to open another one if you have further issues.

**Closed as completed by lewisdonovan** 2024-10-27 20:26 UTC
Labels: bug, in progress
