### ISSUE TITLE
Heroku empty results

### ISSUE THREAD

**Issue by danvoronov** [lewisdonovan/google-news-scraper#16] opened 2021-10-11 21:35 UTC
May be google have some protection on Heroku IP? Or GDPR prompt?

Instead of page with news Puppeteer return to me some weird page with a lot of js script. I see inside code like

> jsdata="deferred-i1" data-p="%.@.[[null,null,&quot;https://consent.google.com/d?continue\u003dhttps://news.google.com/search?

 and then my query.

Just going to consent.google.com end's with 404 page

**Comment by danvoronov** [comment] 2021-10-11 22:00
Ok. This problem only valid if you create app-dyno in Region 'Europe'. In Region 'United States' all work fine.

**Comment by lewisdonovan** [comment] 2021-10-20 15:50
Hiya, thanks for flagging. I've investigated but haven't been able to identify the cause. I'm going to close the issue, as there's a workaround. Thanks for sharing!

**Closed as completed by lewisdonovan** 2021-10-20 15:50 UTC
